# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: deved29
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: crud-awslambda
# "service" is the name of this project. This will also be added to your AWS resource names.
service: crud-serverless-framework

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: 'arn:aws:dynamodb:us-east-1:488772165638:table/usersTable'


functions:
  get-users:
    handler: get_users/handler.handler
    package:
      patterns:
        - get_users/**
    events:
      - httpApi:
          path: /users
          method: GET

  create-users:
    handler: create_users/handler.handler
    package:
      patterns:
        - create_users/**
    events:
      - httpApi:
          path: /users
          method: POST

  update-users:
    handler: update_users/handler.handler
    package:
      patterns:
        - update_users/**
    events:
      - httpApi:
          path: /users/{id}
          method: PUT

  delete-users:
    handler: delete_users/handler.handler
    package:
      patterns:
        - delete_users/**
    events:
      - httpApi:
          path: /users/{id}
          method: DELETE

plugins:
  - serverless-offline
  - serverless-dynamodb


package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.venv/**'
    - '!env/**'
    - '!__pycache__/**'
    - '!.git/**'
    - '!.env'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - '!.python-version'
    - '!bin/**'
    - '!*.egg-info/**'

custom:
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
  pythonRequirements:
    dockerizePip: false
    slim: true
    strip: true
    usePipenv: false
    pipCmdExtraArgs:
      - "--platform manylinux2014_x86_64"
      - "--upgrade"
    noDeploy:
      - boto3
      - botocore
      - s3transfer

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1